version: "3.9"

services:
  api:
    command: ./api -addr=:8000 -debug

  web:
    ports:
      - 8080:80
    volumes:
      - ./web/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./web/html:/var/www/html
